name: flatpak-build

on: [push, pull_request]

jobs:
  build:

    runs-on: [self-hosted, linux]

    steps:
    - uses: louib/flatpak-action@v1
    - name: updating available system dependencies
      run: sudo apt-get update
    - name: printing flatpak version
      run: flatpak --version
    - name: printing flatpak-builder version
      run: flatpak-builder --version
    - name: adding flathub repo
      run: flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
    - name: installing the flatpak runtime and SDK
      run: flatpak install -y --user flathub org.gnome.Platform/x86_64/3.36 org.gnome.Sdk/x86_64/3.36
    - name: converting manifest to JSON
      run: python3 scripts/yml2json net.louib.2flatpak.yml > net.louib.2flatpak.json
    - name: building the flatpak
      run: flatpak-builder --user --force-clean build net.louib.2flatpak.json
